sudo: required

services:
  - docker

before_script:
  - docker build -t maxmilton/chromium .

script:
  - docker run -v $(pwd):/project --rm maxmilton/chromium --version

# TODO: Automatically trigger a new image on Docker hub or revoke image if failed
